import { ArrowDownToLine, ArrowRight, ArrowUpRight, Asterisk, Check, Cpu, MapPin, Plus } from 'lucide-react'
import { content, projects, type ProjectId } from '../content'
import { ContactLinks } from '../hud/Hud'

function SectionHeading({ index, label, title, accent }: { index: string; label: string; title: string; accent: string }) {
  return <><div className="eyebrow section-eyebrow"><span>{index}</span><i />{label}</div><h2 className="section-title">{title}<br /><span>{accent}</span></h2></>
}

export default function Sections({ onSelect, onHover, onRole, onSkill, onNavigate }: { onSelect: (id: ProjectId) => void; onHover: (id: ProjectId | null) => void; onRole: (index: number) => void; onSkill: (index: number) => void; onNavigate: () => void }) {
  const base = import.meta.env.BASE_URL
  return <main id="main-content">
    <section className="portfolio-section hero" id="overview" aria-labelledby="hero-title">
      <div className="hero-topline"><span><i className="status-light" /> HUMAN INTELLIGENCE. HARDWARE SOUL.</span><span>DJD–2027 / RESEARCH EDITION</span></div>
      <div className="hero-copy">
        <div className="eyebrow hero-intro"><span className="tiny-cross">+</span> MEET THE ENGINEER</div>
        <p className="hero-name">DHRUV JYOTI DAS</p>
        <h1 id="hero-title">Intelligence.<br /><span>Engineered.</span></h1>
        <p className="hero-description">From learning how machines think<br className="desktop-break" /> to building what comes next.</p>
        <p className="hero-disciplines">CS + DATA SCIENCE <i /> ML RESEARCH <i /> SYSTEMS</p>
        <div className="hero-actions"><a className="button button-primary" href="#projects" onClick={onNavigate}>Explore my work <ArrowUpRight size={18} /></a><a className="button button-secondary" href={`${base}${content.resumes.general}`} download>Resume <ArrowDownToLine size={16} /></a></div>
        <div className="hero-location"><MapPin size={12} /><span>{content.location}</span><span className="location-dot">·</span><span>Building beyond the benchmark</span></div>
      </div>
      <div className="gpu-callout"><span className="callout-line" /><div><b>BUILT TO THINK DIFFERENTLY.</b><span>1 curious mind. Infinite possibilities.</span></div><Asterisk size={22} /></div>
      <div className="hero-side-label">DESIGNED IN CODE. DRIVEN BY CURIOSITY.</div>
    </section>

    <section className="portfolio-section" id="about" aria-labelledby="about-title">
      <div className="section-content"><SectionHeading index="02" label="THE SILICON / ABOUT" title="Curiosity at" accent="the core." /><h3 id="about-title" className="sr-only">About Dhruv</h3><div className="about-intro"><div><p className="section-lead">{content.bio}</p><p className="section-body">{content.bioDetail}</p></div><figure className="about-portrait"><img src={`${base}Dhruv_Comic_Image.jpg`} alt="Dhruv reading a comic at a bookstore" decoding="async" /><figcaption>OFF THE CLOCK / STILL CURIOUS</figcaption></figure></div><div className="education-list">{content.education.map(education => <article key={education.school}><Cpu size={18} /><div><h3>{education.school}</h3><p>{education.degree}</p><span>{education.detail}</span></div><span className="education-year">CLASS OF<br /><b>{education.year}</b></span></article>)}</div><a className="text-link" href={`${base}${content.resumes.research}`} download>Download research CV <ArrowDownToLine size={14} /></a></div>
      <div className="zone-caption"><span>DJD–2027</span><p>DUAL DEGREE. SINGLE PURPOSE.</p></div>
    </section>

    <section className="portfolio-section" id="experience" aria-labelledby="experience-title">
      <div className="section-content"><SectionHeading index="03" label="THE POWER STAGES / EXPERIENCE" title="Powered by" accent="real research." /><h3 id="experience-title" className="sr-only">Research experience</h3><div className="experience-list">{content.roles.map((role, index) => <article key={role.name} tabIndex={0} onMouseEnter={() => onRole(index)} onMouseLeave={() => onRole(-1)} onFocus={() => onRole(index)} onBlur={() => onRole(-1)}><div className="role-index">0{index + 1}</div><div className="role-content"><div className="role-top"><h3>{role.name}</h3><ArrowUpRight size={17} /></div><div className="role-meta"><span>{role.title}</span><span>{role.date}</span></div><ul>{role.specs.map(spec => <li key={spec}>{spec}</li>)}</ul><span className="role-tag">{role.tag}</span>{role.resources && <details className="role-resources"><summary>View Samsung research materials</summary><div>{role.resources.map(resource => <a key={resource.url} href={resource.local ? `${base}${encodeURIComponent(resource.url)}` : resource.url} target="_blank" rel="noreferrer">{resource.label}<ArrowUpRight size={14} /></a>)}</div></details>}</div></article>)}</div></div><div className="zone-caption"><span>RESEARCH IN MOTION.</span><p>IDEA → EXPERIMENT → IMPACT</p></div>
    </section>

    <section className="portfolio-section projects-section" id="projects" aria-labelledby="projects-title">
      <div className="section-content"><SectionHeading index="04" label="THE MEMORY BANKS / SELECTED WORK" title="Ideas worth" accent="allocating memory." /><h3 id="projects-title" className="sr-only">Selected projects</h3><p className="section-body">Research that asks better questions.<br />Systems that make the answers useful.</p><div className="project-list">{projects.map((project, index) => <article key={project.id} className={project.id === 'cet-vit' ? 'flagship-project' : ''}>
        <button id={`project-${project.id}`} onClick={() => onSelect(project.id)} onMouseEnter={() => onHover(project.id)} onMouseLeave={() => onHover(null)} onFocus={() => onHover(project.id)} onBlur={() => onHover(null)} aria-label={`Explore ${project.name}`}><div className="project-meta"><span>0{index + 1} / {project.category}</span>{project.id === 'cet-vit' && <span className="flagship-tag"><Asterisk size={10} /> FLAGSHIP</span>}</div><div className="project-title-row"><h3>{project.name}</h3><ArrowUpRight size={23} /></div><p>{project.subtitle}</p>{project.id === 'cet-vit' && <div className="flagship-metrics"><span><b>76.54%</b> CIFAR-100</span><span><b>11,433</b> IMG / SEC</span><span className="flagship-platform">AMD MI300X</span></div>}</button>
        <details className="static-project-detail"><summary>Project details</summary><p>{project.problem}</p><p>{project.approach}</p>{project.highlights && <ul>{project.highlights.map(item => <li key={item}>{item}</li>)}</ul>}<p>{project.metrics.map(metric => `${metric.value} ${metric.label}`).join(' · ')}</p>{project.presentation && <p>{project.presentation.status}. {project.presentation.acronym}: {project.presentation.conference}, {project.presentation.location}. <a href={`${base}${encodeURIComponent(project.presentation.certificate)}`}>View presentation certificate</a></p>}{project.link && <a href={project.link.url}>{project.link.label}</a>}</details>
      </article>)}</div><p className="project-note"><Plus size={12} /> SELECT A MEMORY BANK TO EXPLORE</p></div><div className="zone-caption"><span>GDDR / IDEAS IN MOTION</span><p>HOVER A CHIP. OPEN A POSSIBILITY.</p></div>
    </section>

    <section className="portfolio-section" id="skills" aria-labelledby="skills-title"><div className="section-content"><SectionHeading index="05" label="THE CIRCUIT MAP / TOOLKIT" title="Connected by" accent="capability." /><h3 id="skills-title" className="sr-only">Technical skills</h3><p className="section-body">The tools change. The drive to understand<br />how everything connects doesn’t.</p><div className="skills-list">{content.skills.map((skill, index) => <article key={skill.name} tabIndex={0} onMouseEnter={() => onSkill(index)} onMouseLeave={() => onSkill(-1)} onFocus={() => onSkill(index)} onBlur={() => onSkill(-1)}><div className="skill-heading"><span>0{index + 1}</span><h3>{skill.name}</h3><span className="skill-node" /></div><div className="tech-tags">{skill.items.map(item => <span key={item}>{item}</span>)}</div></article>)}</div></div><div className="zone-caption"><span>FULL STACK. FULL CIRCUIT.</span><p>FROM LOW-LEVEL LOGIC TO HIGH-LEVEL LEARNING.</p></div></section>

    <section className="portfolio-section" id="certifications" aria-labelledby="certifications-title"><div className="section-content"><SectionHeading index="06" label="THE BACKPLATE / CREDENTIALS" title="Backed by" accent="the fundamentals." /><h3 id="certifications-title" className="sr-only">Certifications</h3><p className="section-body">A solid foundation. Room to keep growing.</p><div className="certification-list">{content.certifications.map(cert => <article key={cert.name}><div className="cert-icon"><Check size={19} /></div><div><span>{cert.issuer}</span><h3>{cert.name}</h3><p>{cert.detail}</p></div>{'file' in cert && cert.file && <a className="cert-proof" href={`${base}${encodeURIComponent(cert.file)}`} target="_blank" rel="noreferrer" aria-label={`View ${cert.name} certificate`}>View certificate <ArrowUpRight size={14} /></a>}<span className="cert-code">{cert.code}</span></article>)}</div><div className="recommendations"><h3>Letters of recommendation</h3><p>From research and faculty mentors at SRM Institute of Science and Technology.</p><div>{content.recommendations.map(letter => <a key={letter.file} href={`${base}${encodeURIComponent(letter.file)}`} target="_blank" rel="noreferrer"><span><strong>{letter.name}</strong><small>{letter.context}</small></span><span>View letter <ArrowUpRight size={15} /></span></a>)}</div></div></div><div className="zone-caption"><span>VALIDATED. NEVER FINISHED.</span><p>LEARNING IS THE ONLY CONSTANT.</p></div></section>

    <section className="portfolio-section contact-section" id="contact" aria-labelledby="contact-title"><div className="section-content"><div className="eyebrow section-eyebrow"><span>07</span><i />THE CONNECTOR / WHAT’S NEXT</div><h2 id="contact-title" className="section-title">Plug in.<br /><span>Let’s build.</span></h2><p className="section-lead">Let’s compute something great.</p><p className="section-body">An interesting research question, a system worth building,<br />or a conversation that could lead somewhere.</p><ContactLinks /><a className="text-link" href={`${base}${content.resumes.general}`} download>Take my resume with you <ArrowDownToLine size={14} /></a></div><div className="zone-caption"><span>THE NEXT CONNECTION STARTS HERE.</span><ArrowRight size={30} /></div><footer className="site-footer"><span>© 2026 {content.name}</span><span>Rendered in real time. Built with intention.</span><a href="#overview" onClick={onNavigate}>BACK TO THE CORE <ArrowUpRight size={12} /></a></footer></section>
  </main>
}
